name: untitled
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  pdf: ^3.10.1

  fl_chart: ^0.65.0


  path: ^1.8.3
  path_provider: ^2.1.1

  permission_handler: ^11.3.0

  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
 # firebase_app_check: ^0.2.1+3




  get_storage: ^2.1.1

  json_annotation: ^4.9.0





  firebase_core: ^3.13.0

  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  device_preview: ^1.2.0
  shared_preferences: ^2.2.2
 # calendar_agenda:
#    path: dev_lib/calendar_agenda
#  calendar_slider: ^0.0.4



  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/tracker.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true

  assets:
    - assets/img/
    - assets/font/Roboto-Regular.ttf



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600


        - asset: assets/font/Inter-Bold.ttf
          weight: 700

